function squish {
  if [ -z "$1" ]; then
    BRANCH=origin/master
  else
    BRANCH=$1
  fi
  git rebase -i $(git merge-base -a HEAD $BRANCH)
}

toggle-audio () {
	if [[ "$(SwitchAudioSource -c)" == "Shure MV7" ]]
	then
		SwitchAudioSource -s 'CalDigit TS4 Audio - Rear'
	else
		SwitchAudioSource -s 'Shure MV7'
	fi
}

# Enable kubectl autocompletion
source <(kubectl completion zsh)
compdef kubecolor=kubectl

bindkey '^a' autosuggest-accept
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#8ce6e6"


