package lima

import (
	"bytes"
	"text/template"
)

type ProvisionConfig struct {
	User string

	// ProjectPath is the absolute path where Mutagen syncs the project.
	// The provision script creates this directory so Mutagen can sync into it.
	ProjectPath         string
	HostClaudeMountRoot string

	// Flox: .deb from downloads.flox.dev
	FloxVersion string
	FloxURL     string
	FloxSHA256  string

	// Claude Code: standalone binary from Anthropic GCS
	ClaudeVersion string
	ClaudeURL     string
	ClaudeSHA256  string

	// Seeded AGENTS.md content
	AgentsMarkdown string

	// ClaudeSubpaths are the ~/.claude subdirectories to bind-mount into the VM.
	// Must be directories. Populated from mounts.ClaudeSubpaths by the caller.
	ClaudeSubpaths []string

	// SettingsJSON is the content of ~/.claude/settings.json to write into the
	// VM.  Adapted from the host's settings with VM-specific paths (e.g.
	// statusline command pointing to /usr/local/bin/claude-statusline).
	SettingsJSON string
	// omp (Oh My Pi): standalone binary from GitHub releases
	OmpVersion string
	OmpURL     string
	OmpSHA256  string

	// HostOmpMountRoot is the VM path where host omp config subdirs are mounted.
	HostOmpMountRoot string

	// OmpSubpaths are the ~/.config/omp/agent subdirectories to bind-mount.
	OmpSubpaths []string

	// OmpConfigYAML is the content of config.yml to write into the VM.
	// Adapted from the host's config with VM-specific paths.
	OmpConfigYAML string

	// OmpAgentsMarkdown is the AGENTS.md content for omp in the VM.
	OmpAgentsMarkdown string
}

const provisionTmpl = `#!/usr/bin/env bash
set -euo pipefail

# Resolve the actual home directory for the user — Lima may create it as
# /home/<user>.linux, not /home/<user>.
USER_HOME=$(getent passwd {{.User}} | cut -d: -f6)
if [ -z "$USER_HOME" ]; then
  USER_HOME="/home/{{.User}}"
fi
HOST_CLAUDE="{{.HostClaudeMountRoot}}"

# ── Project sync target ──────────────────────────────────────────────────────
# Mutagen syncs the project to the same absolute path as on the host. The
# parent directories must exist before Mutagen can create the sync root.
{{- if .ProjectPath}}
install -d -o {{.User}} -g {{.User}} "{{.ProjectPath}}"
{{- end}}

# ── ~/.claude RO overlay ──────────────────────────────────────────────────────
mkdir -p "$USER_HOME/.claude"
chown -R {{.User}}:{{.User}} "$USER_HOME/.claude"

{{range .Subs}}if [ -e "$HOST_CLAUDE/{{.}}" ]; then
  if [ -d "$HOST_CLAUDE/{{.}}" ]; then mkdir -p "$USER_HOME/.claude/{{.}}"; else [ -e "$USER_HOME/.claude/{{.}}" ] || touch "$USER_HOME/.claude/{{.}}"; fi
  mountpoint -q "$USER_HOME/.claude/{{.}}" || mount --bind -o ro "$HOST_CLAUDE/{{.}}" "$USER_HOME/.claude/{{.}}"
fi
{{end}}

install -d /etc/sandbox

# systemd unit for overlay re-apply on every boot
cat > /etc/systemd/system/sandbox-claude-overlay.service <<'UNIT'
[Unit]
Description=Re-apply ~/.claude RO overlay bind mounts
After=local-fs.target lima-mounts.target

[Service]
Type=oneshot
ExecStart=/etc/sandbox/apply-claude-overlay.sh

[Install]
WantedBy=multi-user.target
UNIT

# Write the overlay apply script without a heredoc — use printf so the
# per-subpath commands (generated by template range) land inline.
printf '#!/usr/bin/env bash\nset -euo pipefail\nUSER_HOME="/home/{{.User}}"\nHOST_CLAUDE="{{.HostClaudeMountRoot}}"\nHOST_OMP="{{.HostOmpMountRoot}}"\n{{range .Subs}}if [ -e "$HOST_CLAUDE/{{.}}" ] && ! mountpoint -q "$USER_HOME/.claude/{{.}}"; then\n  if [ -d "$HOST_CLAUDE/{{.}}" ]; then mkdir -p "$USER_HOME/.claude/{{.}}"; else [ -e "$USER_HOME/.claude/{{.}}" ] || touch "$USER_HOME/.claude/{{.}}"; fi\n  mount --bind -o ro "$HOST_CLAUDE/{{.}}" "$USER_HOME/.claude/{{.}}"\nfi\n{{end}}{{range .OmpSubs}}if [ -e "$HOST_OMP/{{.}}" ] && ! mountpoint -q "$USER_HOME/.config/omp/agent/{{.}}"; then\n  if [ -d "$HOST_OMP/{{.}}" ]; then mkdir -p "$USER_HOME/.config/omp/agent/{{.}}"; else [ -e "$USER_HOME/.config/omp/agent/{{.}}" ] || touch "$USER_HOME/.config/omp/agent/{{.}}"; fi\n  mount --bind -o ro "$HOST_OMP/{{.}}" "$USER_HOME/.config/omp/agent/{{.}}"\nfi\n{{end}}' > /etc/sandbox/apply-claude-overlay.sh

systemctl daemon-reload
systemctl enable sandbox-claude-overlay.service

# ── Nix ───────────────────────────────────────────────────────────────────────
if [ ! -d /nix ]; then
  # Lima system provisioning runs as root without $HOME set (cloud-init).
  # The Nix installer requires $HOME; export it for this block.
  export HOME="${HOME:-/root}"
  curl -L https://nixos.org/nix/install | sh -s -- --daemon --yes
fi
. /etc/profile.d/nix.sh

# ── Seed /nix/store from warm template ──────────────────────────────────────
if [ -d /var/sandbox/warm-nix/store ]; then
  echo "seeding /nix/store from warm template…"
  rsync -aH --ignore-existing /var/sandbox/warm-nix/store/ /nix/store/
fi

# ── Flox ──────────────────────────────────────────────────────────────────────
if ! command -v flox >/dev/null 2>&1; then
  TMPF=$(mktemp -t flox.deb.XXXXXX)
  curl -fsSL "{{.FloxURL}}" -o "$TMPF"
  echo "{{.FloxSHA256}}  $TMPF" | sha256sum -c -
  # Install via dpkg so postinst scripts unpack the bundled Nix closure
  # into /nix/store. Manual extraction (dpkg-deb -x) skips scripts and
  # leaves dangling symlinks.
  dpkg -i "$TMPF" || true   # may report unmet deps; flox still works
  rm -f "$TMPF"
fi

# ── Claude Code ───────────────────────────────────────────────────────────────
if ! command -v claude >/dev/null 2>&1; then
  TMPC=$(mktemp -t claude.XXXXXX)
  curl -fsSL "{{.ClaudeURL}}" -o "$TMPC"
  echo "{{.ClaudeSHA256}}  $TMPC" | sha256sum -c -
  install -m 0755 "$TMPC" /usr/local/bin/claude
  rm -f "$TMPC"
  # Some Claude builds use a Nix store ELF interpreter that doesn't exist in
  # the VM. If detected, symlink it to the system dynamic linker.
  INTERP=$(dd if=/usr/local/bin/claude bs=4096 count=1 2>/dev/null | tr '\0' '\n' | grep '/nix/store.*ld-linux' | head -1 || true)
  if [ -n "$INTERP" ] && [ ! -e "$INTERP" ]; then
    mkdir -p "$(dirname "$INTERP")"
    SYS_LD=$(ls /lib/ld-linux-* 2>/dev/null | head -1 || true)
    [ -n "$SYS_LD" ] && ln -sf "$SYS_LD" "$INTERP"
  fi
fi

# ── CLAUDE.md (global agent instructions) ────────────────────────────────────
mkdir -p /etc/sandbox
cat > /etc/sandbox/CLAUDE.md <<'CLAUDE_MD_EOF'
{{.AgentsMarkdown}}
CLAUDE_MD_EOF

# Seed the global CLAUDE.md that Claude Code discovers on startup.
mkdir -p "$USER_HOME/.claude"
ln -sfn /etc/sandbox/CLAUDE.md "$USER_HOME/.claude/CLAUDE.md" 2>/dev/null || true
# No chown here: the chown above (before bind mounts) covers ~/.claude. A
# second chown after the RO overlays would traverse the read-only mountpoints
# and fail with "Operation not permitted" (D-I-1).


# ── Claude wrapper ───────────────────────────────────────────────────────────
if [ -x /var/sandbox/bin/sandbox-claude ]; then
  # First time: rename the real claude binary so the wrapper can call it.
  if [ -x /usr/local/bin/claude ] && [ ! -x /usr/local/bin/claude.real ]; then
    mv /usr/local/bin/claude /usr/local/bin/claude.real
  fi
  install -m 0755 /var/sandbox/bin/sandbox-claude /usr/local/bin/claude
  # Fix Nix-store ELF interpreter in the wrapper, same as the claude binary above.
  WINTERP=$(dd if=/usr/local/bin/claude bs=4096 count=1 2>/dev/null | tr '\0' '\n' | grep '/nix/store.*ld-linux' | head -1 || true)
  if [ -n "$WINTERP" ] && [ ! -e "$WINTERP" ]; then
    mkdir -p "$(dirname "$WINTERP")"
    SYS_LD=$(ls /lib/ld-linux-* 2>/dev/null | head -1 || true)
    [ -n "$SYS_LD" ] && ln -sf "$SYS_LD" "$WINTERP"
  fi
fi

# ── Claude statusline binary ─────────────────────────────────────────────────
if [ -x /var/sandbox/bin/claude-statusline ]; then
  install -m 0755 /var/sandbox/bin/claude-statusline /usr/local/bin/claude-statusline
  # Fix Nix-store ELF interpreter, same pattern as other binaries.
  SINTERP=$(dd if=/usr/local/bin/claude-statusline bs=4096 count=1 2>/dev/null | tr '\0' '\n' | grep '/nix/store.*ld-linux' | head -1 || true)
  if [ -n "$SINTERP" ] && [ ! -e "$SINTERP" ]; then
    mkdir -p "$(dirname "$SINTERP")"
    SYS_LD=$(ls /lib/ld-linux-* 2>/dev/null | head -1 || true)
    [ -n "$SYS_LD" ] && ln -sf "$SYS_LD" "$SINTERP"
  fi
fi

# ── Claude settings.json (statusline + user preferences) ─────────────────────
# Write the VM settings that reference the installed statusline binary.
# The wrapper already handles --dangerously-skip-permissions, so we omit
# the permissions block.  This file is written every provision so re-creating
# the VM picks up settings changes.
{{- if .SettingsJSON}}
cat > "$USER_HOME/.claude/settings.json" <<'SETTINGS_EOF'
{{.SettingsJSON}}
SETTINGS_EOF
chown {{.User}}:{{.User}} "$USER_HOME/.claude/settings.json"
{{- end}}
# ── omp (Oh My Pi) ──────────────────────────────────────────────────────────
{{- if .OmpURL}}
if ! command -v omp >/dev/null 2>&1; then
  TMPO=$(mktemp -t omp.XXXXXX)
  curl -fsSL "{{.OmpURL}}" -o "$TMPO"
  echo "{{.OmpSHA256}}  $TMPO" | sha256sum -c -
  install -m 0755 "$TMPO" /usr/local/bin/omp
  rm -f "$TMPO"
  # Fix Nix-store ELF interpreter if present (same pattern as Claude binary).
  OINTERP=$(dd if=/usr/local/bin/omp bs=4096 count=1 2>/dev/null | tr '\0' '\n' | grep '/nix/store.*ld-linux' | head -1 || true)
  if [ -n "$OINTERP" ] && [ ! -e "$OINTERP" ]; then
    mkdir -p "$(dirname "$OINTERP")"
    SYS_LD=$(ls /lib/ld-linux-* 2>/dev/null | head -1 || true)
    [ -n "$SYS_LD" ] && ln -sf "$SYS_LD" "$OINTERP"
  fi
fi
{{- end}}

# ── omp config ──────────────────────────────────────────────────────────────
mkdir -p "$USER_HOME/.config/omp/agent"
mkdir -p "$USER_HOME/.local/state/omp/sessions"
chown -R {{.User}}:{{.User}} "$USER_HOME/.config/omp"
chown -R {{.User}}:{{.User}} "$USER_HOME/.local/state/omp"

{{- if .OmpConfigYAML}}
cat > "$USER_HOME/.config/omp/agent/config.yml" <<'OMP_CONFIG_EOF'
{{.OmpConfigYAML}}
OMP_CONFIG_EOF
chown {{.User}}:{{.User}} "$USER_HOME/.config/omp/agent/config.yml"
{{- end}}

{{- if .OmpAgentsMarkdown}}
cat > "$USER_HOME/.config/omp/agent/AGENTS.md" <<'OMP_AGENTS_EOF'
{{.OmpAgentsMarkdown}}
OMP_AGENTS_EOF
chown {{.User}}:{{.User}} "$USER_HOME/.config/omp/agent/AGENTS.md"
{{- end}}

# ── omp RO overlay ──────────────────────────────────────────────────────────
{{- if .HostOmpMountRoot}}
HOST_OMP="{{.HostOmpMountRoot}}"
{{range .OmpSubs}}if [ -e "$HOST_OMP/{{.}}" ]; then
  if [ -d "$HOST_OMP/{{.}}" ]; then mkdir -p "$USER_HOME/.config/omp/agent/{{.}}"; else [ -e "$USER_HOME/.config/omp/agent/{{.}}" ] || touch "$USER_HOME/.config/omp/agent/{{.}}"; fi
  mountpoint -q "$USER_HOME/.config/omp/agent/{{.}}" || mount --bind -o ro "$HOST_OMP/{{.}}" "$USER_HOME/.config/omp/agent/{{.}}"
fi
{{end}}
{{- end}}

# ── omp environment variables ──────────────────────────────────────────────
cat > /etc/profile.d/omp-env.sh <<'OMP_ENV'
export PI_CODING_AGENT_DIR="$HOME/.config/omp/agent"
export PI_CONFIG_DIR=".config/omp"
OMP_ENV

# ── sandbox-helper unit (placeholder; Phase 9 fills the ExecStart) ───────────
cat > /etc/systemd/system/sandbox-helper.service <<'HELPER_UNIT'
[Unit]
Description=sandbox helper bridge agent (placeholder)
After=network.target

[Service]
Type=simple
ExecStart=/bin/sh -c 'while true; do sleep 86400; done'
Restart=on-failure

[Install]
WantedBy=multi-user.target
HELPER_UNIT
systemctl daemon-reload
systemctl enable sandbox-helper.service

# ── sshd: allow unix socket forwarding (Phase 9 needs StreamLocalBindUnlink) ──
if ! grep -q 'StreamLocalBindUnlink' /etc/ssh/sshd_config 2>/dev/null; then
  echo 'StreamLocalBindUnlink yes' >> /etc/ssh/sshd_config
  systemctl restart sshd 2>/dev/null || true
fi

# ── PATH: ensure ~/.local/bin is available ────────────────────────────────────
cat > /etc/profile.d/local-bin.sh <<'LOCALBIN'
if [ -d "$HOME/.local/bin" ]; then
  case ":$PATH:" in
    *":$HOME/.local/bin:"*) ;;
    *) export PATH="$HOME/.local/bin:$PATH" ;;
  esac
fi
LOCALBIN

# ── bridge socket directory ──────────────────────────────────────────────────
# SSH -R forwards create the socket as the authenticated user, so the parent
# directory must be user-writable. /run/ is a tmpfs cleared on reboot, so we
# persist via tmpfiles.d.
install -d -m 0755 -o {{.User}} -g {{.User}} /run/sandbox
cat > /etc/tmpfiles.d/sandbox.conf <<TMPFILES
d /run/sandbox 0755 {{.User}} {{.User}} -
TMPFILES
`

// RenderProvision produces the first-boot provision script. It installs:
//   - ~/.claude RO overlay (bind-mounts from /var/sandbox/host-claude/)
//   - Nix multi-user daemon
//   - Seed /nix/store from warm template (if /var/sandbox/warm-nix/store exists)
//   - Flox from .deb package
//   - Claude Code standalone binary
//   - /etc/sandbox/CLAUDE.md and ~/.claude/CLAUDE.md symlink
//   - sandbox-helper.service placeholder
//   - sshd StreamLocalBindUnlink for Phase 9 bridge forwarding
func RenderProvision(cfg ProvisionConfig) (string, error) {
	t, err := template.New("p").Parse(provisionTmpl)
	if err != nil {
		return "", err
	}
	var b bytes.Buffer
	if err := t.Execute(&b, struct {
		ProvisionConfig
		Subs    []string
		OmpSubs []string
	}{cfg, cfg.ClaudeSubpaths, cfg.OmpSubpaths}); err != nil {
	}
	return b.String(), nil
}
